# Site settings
title: Hjelfman
tag_text: Hjelfman
description: Hjelfman
# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
plugins:
  - jekyll-sitemap
remote-theme: clean-jekyll-theme
