title: John Doe
name: John Doe
description: Small site for projects.
permalink: /posts/:year/:month/:day/:title/

baseurl: "/"
url: ""
lang: "en"

github_username: ethanhelfman

social:
    name: Ethan Helfman
    links:
        - https://github.com/ethanhelfman

# Build settings
markdown: kramdown
theme: clean-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
