title: the butterfly conservatory
name: hjelfman
description: writing repository
permalink: /posts/:year/:month/:day/:title/

baseurl: "/"
url: ""
lang: "en"

github_username: hjelfman

social:
    name: Hazel Helfman
    links:
        - https://github.com/hjelfman

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
