title: Hazelwood
name: hjelfman
description: Posts and projects
permalink: /posts/:year/:month/:day/:title/

baseurl: "/"
url: ""
lang: "en"

theme: clean-jekyll-theme
github_username: hjelfman

social:
    name: Ethan Helfman
    links:
        - https://github.com/hjelfman

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
